### ISSUE TITLE
Possible Issue

### ISSUE THREAD

**Issue by xXTheBigBearXx** [FTBTeam/FTB-Zombies#3]
Large Rusty Iron Double Doors are instantly breakable, not sure if intended or not.

**Comment by modmuss50** [comment]
I could most likely disable all block breaking as I don’t think it’s required in the map.

**Comment by xXTheBigBearXx** [comment]
I saw no use for it while playing, but I think there may be some leaves you can get stuck in?

**Comment by modmuss50** [comment]
This has been fixed in future versions of the pack
